name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    name: Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rustup components
        run: |
          rustup component add clippy --toolchain nightly
          rustup component add rustfmt --toolchain nightly

      - name: Build
        run: cargo build

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo +nightly tarpaulin --all-features --timeout 120 --out HTML

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: tarpaulin-report.html

